project_id = "ijyqtemnhlbamxmgjuzp"

[functions.send-vendor-email]
verify_jwt = false

[functions.search-streets]
verify_jwt = false

[functions.send-vendor-otp]
verify_jwt = false

[functions.verify-vendor-otp]
verify_jwt = false

[functions.send-vendor-confirmation]
verify_jwt = false

[functions.extract-bank-details]
verify_jwt = false

[functions.vendor-form-api]
verify_jwt = false

[functions.vendor-upload]
verify_jwt = false
