project_id = "ijyqtemnhlbamxmgjuzp"

[functions.send-vendor-email]
verify_jwt = false

[functions.search-streets]
verify_jwt = false

[functions.send-vendor-otp]
verify_jwt = false

[functions.verify-vendor-otp]
verify_jwt = false

[functions.send-vendor-confirmation]
verify_jwt = false

[functions.extract-bank-details]
verify_jwt = false

[functions.extract-document-data]
verify_jwt = false

[functions.vendor-form-api]
verify_jwt = false

[functions.vendor-upload]
verify_jwt = false

[functions.send-approval-request]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.send-manager-approval]
verify_jwt = false

[functions.handle-manager-approval]
verify_jwt = false

[functions.extract-document-text]
verify_jwt = false

[functions.vendor-status]
verify_jwt = false

[functions.send-handler-notification]
verify_jwt = false

[functions.send-vendor-rejection]
verify_jwt = false

[functions.send-receipts-link]
verify_jwt = false
