project_id = "ijyqtemnhlbamxmgjuzp"

[functions.send-vendor-email]
verify_jwt = false

[functions.search-streets]
verify_jwt = false

[functions.send-vendor-otp]
verify_jwt = false

[functions.verify-vendor-otp]
verify_jwt = false